# Generated by Django 3.2.7 on 2021-09-20 13:37

import copo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('in_txt', models.FileField(upload_to=copo.models.upload_to_in)),
                ('out_txt', models.FileField(upload_to=copo.models.upload_to_out)),
            ],
        ),
    ]
